version: "3.8"

services:

  db:
    image: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server