name: Run linter

# TODO:
# Protect main and do changes to it from pr only and run this action on any other branchs' push event
# Make main branch it's own action script that does checks and builds publish version and publishes it.
# Because main is protected build action is then only run when pr is merged into it.
on:
  push:
    branches-ignore:
      - "main"


jobs:
  linter-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ server, whiteboard-client ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get correct Nodejs version
        uses: actions/setup-node@v3
        with:
          node-version: '19.6'
      - name: Run npm ci for ${{ matrix.dir }}
        run: npm ci
        working-directory: ${{ matrix.dir }}
      - name: Run linter for ${{ matrix.dir }}
        run: npm run eslint
        working-directory: ${{ matrix.dir }}
