name: Run linter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  linter-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ server, whiteboard-client ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get correct Nodejs version
        uses: actions/setup-node@v3
        with:
          node-version: '19.6'
      - name: Run npm ci in ${{ matrix.dir }}
        run: npm ci
        working-directory: ${{ matrix.dir }}
      - name: Run linting in ${{ matrix.dir }}
        run: npm run eslint
        working-directory: ${{ matrix.dir }}

      #- name: npm ci in server
      #  run: npm ci
      #  working-directory: ./server
      #- name: npm eslint on ./server
      #  run: npm run eslint
      #  working-directory: ./server
      #- name: npm ci in whiteboard-client
      #  run: npm ci
      #  working-directory: ./whiteboard-client
      #- name: npm eslint on whiteboard-client
      #  run: npm run eslint
      #  working-directory: ./whiteboard-client


